### ISSUE TITLE
Python basics #1

### ISSUE THREAD

**Issue by kirkster96** [General-Blue/Intro-to-Python#1]
Here is what I have in mind to go over in our next meeting:

- [ ] print function
- [ ] input function
- [ ] importing libraries
- [ ] creating variables
- [ ] performing math operations

I am going to clean up the repo and add py_basics_1.py to the repo with some skeleton code to get us started next time. Please install python 3 on your machine if you find some time between now and next week. Leave a comment here if you have any questions!

**Comment by General-Blue** [comment]
In our meeting today we completed all of the tasks listed, and started working on Python basics #2.
